### ISSUE TITLE
张雅仁_2016.2.8-2016.2.11时间规划表/任务分配表

### ISSUE THREAD

**Issue by ghost** [spacegoing/Pomodoro_Python#9]
# 任务分配表
## 共同任务
- 批斗大会整理与继续思考互相批评（整理已完成，仍需继续思考互相批评）
- 实验室项目管理制度（已完成）
## 张雅仁
- 使用pomodoro_python并不断更新、修改建议
- 重学gitpro（已完成）
- 实现pomodoro one（功能已借助李畅学长的代码基本实现，还有一些优化与refactor）
- 每日教雷云Python （正在进行）
- （可选，若太耗时则可暂时不做）team services
## 雷云
- 学习Git + Github
- 使用pomodoro_python并不断更新、修改建议
- 学习Python
# 时间规划表
## 张雅仁

**\- 2016.2.7**
- 整理批斗大会，整理实验室项目管理制度
- 重看gitpro：六个番茄 共三章，第一章一个番茄 第二章二个番茄 第三章三个番茄 
- 初步复习python 相关语法：二个小时
- 与雷云交流学习情况：一个小时

**\- 2016.2.8**
- 继续复习python语法：10个番茄
- 开始实现pomodoro one
- 解答雷云git/github和python的疑惑：一个小时

**\- 2016.2.9——2016.2.11**
- 实现pomodoro one，每天12个番茄工作时间
- 解答雷云git/github和python的疑惑：一个小时
## 雷云

**\- 2016.2.7——2016.2.8**
- 整理批斗大会和实验室项目管理制度
- 练习使用git和github，每天10个番茄时间
- 使用番茄工作法，实时写下使用反馈

**\- 2016.2.9——2016.2.11**
- 学习Python，每天10个番茄
- 请教张雅仁，解决疑惑，每天1个番茄
- 使用番茄工作法，实时写下使用反馈

**Comment by ghost** [comment]
# 每日规划 2016.2.7

## 张雅仁
- 整理批斗大会，整理实验室项目管理制度
- 重看gitpro：六个番茄 共三章，第一章一个番茄 第二章二个番茄 第三章三个番茄
- 初步复习python 相关语法：二个小时
- 与雷云交流学习情况：一个小时

## 雷云
- 协助张雅仁整理批斗大会内容，并编撰实验室项目管理制度初稿。整理内容两个番茄，编写管理制度一个番茄。（已完成）
- 熟悉gitpro操作：两个番茄（已完成）

**Comment by ghost** [comment]
# 每日规划 2016.2.8

## 张雅仁
- 复习python 相关语法：十个番茄（已完成）
- 开始实现pomodoro one
- 与雷云交流学习情况，解答雷云git/github的疑惑：一个小时

## 雷云
- 继续复习gitpro：两个番茄（已完成）
- 第二次观看github使用说明：三个番茄（未完成：年初一——初三强制拜年，晚间学习效率低）
- 与张雅仁交流复习难点，排除gitpro和github的难点：两个番茄（未完成）

**Comment by ghost** [comment]
# 每日规划 2016.2.9

## 张雅仁
- 复习python 相关语法：二个番茄(已完成)
- 运行好pycharm: 一个番茄（已完成）
- 开始实现pomodoro one（正在进行，阅读代码和参考资料）
- 与雷云交流学习情况，解答雷云git/github的疑惑：一个小时

## 雷云
- 第二次观看github使用说明：三个番茄（未完成）
- 与张雅仁交流复习难点，排除github的难点（未完成）

## 李畅

已经完成Interactive Console Shortcuts 并merge到master。
张雅仁需要pull我最新的master branch，并阅读pomo_alarm() 以及KbdListerner class。
之后凡是需要快捷键操作的内容均需在KbdListerner 的 shortcut_callbacks(self, stdin, mask) 下注册。

只需要学会修改shortcut_callbacks（添加if条件），不需要完全明白新添加的代码。

参考资料：https://github.com/spacegoing/Pomodoro_Python/issues/8
- 使用selectors监听键盘：KbdListerner的run()，参见链接中Key board Listener标题
- 多线程并行：Alarm.py 和KeaboardListener.py，参见Multi-threading (Pause & Resume)
- 记录、擦除已经打印在console中的文字：参见 class LSTN_IO

**Comment by spacegoing** [comment]
# 每日规划 2016.2.10

## 张雅仁
- 实现pomodoro one ，阅读代码和资料，实现基本功能
- refactor code 

## 雷云
- 最后一次复习gitpro前三章，4个番茄（未完成，白天拜年，晚上回来开会，确认各自项目进度）

## 李畅

防止你们没看到：Pycharm看代码方便的工具
- Command+7 Structure view
- Control+Alt+H Hierarchy view
- https://www.jetbrains.com/pycharm/help/analyzing-applications.html

**Comment by RayGod** [comment]
# 每日规划 2016.2.11

## 张雅仁
- 有没有什么办法让每日具体规划倒叙排列或者置顶，免得每次都要拉到最下面
- 最好的办法就是用MTFS，先这么用着github等番茄写完了我们学一下MTFS以后用那个
- 争取完成pomodoro_one（已完成）
- 对写代码过程中发现的python语法等疑问 github疑问查漏补缺（未完成）
- 教雷云 github（未完成，还需仔细对着教）

## 雷云
- 学习github第三个视频，三个番茄（未完成）

## 李畅
- 学长能不能把今天修改的实验室规章制度word发到群里
- 我没保存，思路你们听懂了具体方法不比完全按照我说的来

**Comment by ghost** [comment]
# 每日规划 2016.2.12

## 张雅仁
- 确定会议时间，进行人民公饭项目的讨论（已完成）
- 继续对写代码过程中发现的python语法等疑问 github疑问查漏补缺（基本已完成，还需一个番茄）
- 仔细认真帮助雷云学习 github python

## 雷云

## 李畅
